name: Publish Plugin to Portal

on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_MAVEN_PUBLISH_KEY: ${{ secrets.GRADLE_MAVEN_PUBLISH_KEY }}
      GRADLE_MAVEN_PUBLISH_SECRET: ${{ secrets.GRADLE_MAVEN_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue
      - name: Publish
        run: ./gradlew --project-dir plugin-build publish
        if: success()
